/*
 * Data structures for Home Assistant MQTT discovery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ButtonDeviceIdentifiers {
}

impl ButtonDeviceIdentifiers {
    pub fn new() -> ButtonDeviceIdentifiers {
        ButtonDeviceIdentifiers {
        }
    }
}


