/*
 * Data structures for Home Assistant MQTT discovery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Fan {
    /// A list of MQTT topics subscribed to receive availability (online/offline) updates. Must not be used together with `availability_topic`.
    #[serde(rename = "availability", skip_serializing_if = "Option::is_none")]
    pub availability: Option<Vec<crate::models::AlarmControlPanelAvailabilityInner>>,
    /// When `availability` is configured, this controls the conditions needed to set the entity to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payload_available` must be received on all configured availability topics before the entity is marked as online. If set to `any`, `payload_available` must be received on at least one configured availability topic before the entity is marked as online. If set to `latest`, the last `payload_available` or `payload_not_available` received on any configured availability topic controls the availability. (Default: `latest)`
    #[serde(rename = "availability_mode", skip_serializing_if = "Option::is_none")]
    pub availability_mode: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract device's availability from the `availability_topic`. To determine the devices's availability result of this template will be compared to `payload_available` and `payload_not_available`.
    #[serde(rename = "availability_template", skip_serializing_if = "Option::is_none")]
    pub availability_template: Option<String>,
    /// The MQTT topic subscribed to receive availability (online/offline) updates. Must not be used together with `availability`.
    #[serde(rename = "availability_topic", skip_serializing_if = "Option::is_none")]
    pub availability_topic: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to generate the payload to send to `command_topic`.
    #[serde(rename = "command_template", skip_serializing_if = "Option::is_none")]
    pub command_template: Option<String>,
    /// The MQTT topic to publish commands to change the fan state.
    #[serde(rename = "command_topic")]
    pub command_topic: String,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<Box<crate::models::FanDevice>>,
    /// Flag which defines if the entity should be enabled when first added. (Default: `true)`
    #[serde(rename = "enabled_by_default", skip_serializing_if = "Option::is_none")]
    pub enabled_by_default: Option<bool>,
    /// The encoding of the payloads received and published messages. Set to `\"\"` to disable decoding of incoming payload. (Default: `utf-8)`
    #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    /// The [category](https://developers.home-assistant.io/docs/core/entity#generic-properties) of the entity. (Default: `None)`
    #[serde(rename = "entity_category", skip_serializing_if = "Option::is_none")]
    pub entity_category: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract the JSON dictionary from messages received on the `json_attributes_topic`. Usage example can be found in [MQTT sensor](/integrations/sensor.mqtt/#json-attributes-template-configuration) documentation.
    #[serde(rename = "json_attributes_template", skip_serializing_if = "Option::is_none")]
    pub json_attributes_template: Option<String>,
    /// The MQTT topic subscribed to receive a JSON dictionary payload and then set as sensor attributes. Usage example can be found in [MQTT sensor](/integrations/sensor.mqtt/#json-attributes-topic-configuration) documentation.
    #[serde(rename = "json_attributes_topic", skip_serializing_if = "Option::is_none")]
    pub json_attributes_topic: Option<String>,
    /// The name of the fan. Can be set to `null` if only the device name is relevant. (Default: `MQTT Fan)`
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Used instead of `name` for automatic generation of `entity_id`
    #[serde(rename = "object_id", skip_serializing_if = "Option::is_none")]
    pub object_id: Option<String>,
    /// Flag that defines if fan works in optimistic mode (Default: ``true` if no state topic defined, else `false`.)`
    #[serde(rename = "optimistic", skip_serializing_if = "Option::is_none")]
    pub optimistic: Option<bool>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to generate the payload to send to `direction_command_topic`.
    #[serde(rename = "direction_command_template", skip_serializing_if = "Option::is_none")]
    pub direction_command_template: Option<String>,
    /// The MQTT topic to publish commands to change the direction state.
    #[serde(rename = "direction_command_topic", skip_serializing_if = "Option::is_none")]
    pub direction_command_topic: Option<String>,
    /// The MQTT topic subscribed to receive direction state updates.
    #[serde(rename = "direction_state_topic", skip_serializing_if = "Option::is_none")]
    pub direction_state_topic: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract a value from the direction.
    #[serde(rename = "direction_value_template", skip_serializing_if = "Option::is_none")]
    pub direction_value_template: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to generate the payload to send to `oscillation_command_topic`.
    #[serde(rename = "oscillation_command_template", skip_serializing_if = "Option::is_none")]
    pub oscillation_command_template: Option<String>,
    /// The MQTT topic to publish commands to change the oscillation state.
    #[serde(rename = "oscillation_command_topic", skip_serializing_if = "Option::is_none")]
    pub oscillation_command_topic: Option<String>,
    /// The MQTT topic subscribed to receive oscillation state updates.
    #[serde(rename = "oscillation_state_topic", skip_serializing_if = "Option::is_none")]
    pub oscillation_state_topic: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract a value from the oscillation.
    #[serde(rename = "oscillation_value_template", skip_serializing_if = "Option::is_none")]
    pub oscillation_value_template: Option<String>,
    /// The payload that represents the available state. (Default: `online)`
    #[serde(rename = "payload_available", skip_serializing_if = "Option::is_none")]
    pub payload_available: Option<String>,
    /// The payload that represents the unavailable state. (Default: `offline)`
    #[serde(rename = "payload_not_available", skip_serializing_if = "Option::is_none")]
    pub payload_not_available: Option<String>,
    /// The payload that represents the stop state. (Default: `OFF)`
    #[serde(rename = "payload_off", skip_serializing_if = "Option::is_none")]
    pub payload_off: Option<String>,
    /// The payload that represents the running state. (Default: `ON)`
    #[serde(rename = "payload_on", skip_serializing_if = "Option::is_none")]
    pub payload_on: Option<String>,
    /// The payload that represents the oscillation off state. (Default: `oscillate_off)`
    #[serde(rename = "payload_oscillation_off", skip_serializing_if = "Option::is_none")]
    pub payload_oscillation_off: Option<String>,
    /// The payload that represents the oscillation on state. (Default: `oscillate_on)`
    #[serde(rename = "payload_oscillation_on", skip_serializing_if = "Option::is_none")]
    pub payload_oscillation_on: Option<String>,
    /// A special payload that resets the `percentage` state attribute to `unknown` when received at the `percentage_state_topic`. (Default: `None)`
    #[serde(rename = "payload_reset_percentage", skip_serializing_if = "Option::is_none")]
    pub payload_reset_percentage: Option<String>,
    /// A special payload that resets the `preset_mode` state attribute to `unknown` when received at the `preset_mode_state_topic`. (Default: `None)`
    #[serde(rename = "payload_reset_preset_mode", skip_serializing_if = "Option::is_none")]
    pub payload_reset_preset_mode: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to generate the payload to send to `percentage_command_topic`.
    #[serde(rename = "percentage_command_template", skip_serializing_if = "Option::is_none")]
    pub percentage_command_template: Option<String>,
    /// The MQTT topic to publish commands to change the fan speed state based on a percentage.
    #[serde(rename = "percentage_command_topic", skip_serializing_if = "Option::is_none")]
    pub percentage_command_topic: Option<String>,
    /// The MQTT topic subscribed to receive fan speed based on percentage.
    #[serde(rename = "percentage_state_topic", skip_serializing_if = "Option::is_none")]
    pub percentage_state_topic: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract the `percentage` value from the payload received on `percentage_state_topic`.
    #[serde(rename = "percentage_value_template", skip_serializing_if = "Option::is_none")]
    pub percentage_value_template: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to generate the payload to send to `preset_mode_command_topic`.
    #[serde(rename = "preset_mode_command_template", skip_serializing_if = "Option::is_none")]
    pub preset_mode_command_template: Option<String>,
    /// The MQTT topic to publish commands to change the preset mode.
    #[serde(rename = "preset_mode_command_topic", skip_serializing_if = "Option::is_none")]
    pub preset_mode_command_topic: Option<String>,
    /// The MQTT topic subscribed to receive fan speed based on presets.
    #[serde(rename = "preset_mode_state_topic", skip_serializing_if = "Option::is_none")]
    pub preset_mode_state_topic: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract the `preset_mode` value from the payload received on `preset_mode_state_topic`.
    #[serde(rename = "preset_mode_value_template", skip_serializing_if = "Option::is_none")]
    pub preset_mode_value_template: Option<String>,
    #[serde(rename = "preset_modes", skip_serializing_if = "Option::is_none")]
    pub preset_modes: Option<Box<crate::models::FanPresetModes>>,
    /// The maximum QoS level to be used when receiving and publishing messages.
    #[serde(rename = "qos", skip_serializing_if = "Option::is_none")]
    pub qos: Option<i32>,
    /// If the published message should have the retain flag on or not. (Default: `true)`
    #[serde(rename = "retain", skip_serializing_if = "Option::is_none")]
    pub retain: Option<bool>,
    /// The maximum of numeric output range (representing 100 %). The number of speeds within the `speed_range` / `100` will determine the `percentage_step`. (Default: `100)`
    #[serde(rename = "speed_range_max", skip_serializing_if = "Option::is_none")]
    pub speed_range_max: Option<i32>,
    /// The minimum of numeric output range (`off` not included, so `speed_range_min` - `1` represents 0 %). The number of speeds within the speed_range / 100 will determine the `percentage_step`. (Default: `1)`
    #[serde(rename = "speed_range_min", skip_serializing_if = "Option::is_none")]
    pub speed_range_min: Option<i32>,
    /// The MQTT topic subscribed to receive state updates.
    #[serde(rename = "state_topic", skip_serializing_if = "Option::is_none")]
    pub state_topic: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract a value from the state.
    #[serde(rename = "state_value_template", skip_serializing_if = "Option::is_none")]
    pub state_value_template: Option<String>,
    /// An ID that uniquely identifies this fan. If two fans have the same unique ID, Home Assistant will raise an exception.
    #[serde(rename = "unique_id", skip_serializing_if = "Option::is_none")]
    pub unique_id: Option<String>,
}

impl Fan {
    pub fn new(command_topic: String) -> Fan {
        Fan {
            availability: None,
            availability_mode: None,
            availability_template: None,
            availability_topic: None,
            command_template: None,
            command_topic,
            device: None,
            enabled_by_default: None,
            encoding: None,
            entity_category: None,
            json_attributes_template: None,
            json_attributes_topic: None,
            name: None,
            object_id: None,
            optimistic: None,
            direction_command_template: None,
            direction_command_topic: None,
            direction_state_topic: None,
            direction_value_template: None,
            oscillation_command_template: None,
            oscillation_command_topic: None,
            oscillation_state_topic: None,
            oscillation_value_template: None,
            payload_available: None,
            payload_not_available: None,
            payload_off: None,
            payload_on: None,
            payload_oscillation_off: None,
            payload_oscillation_on: None,
            payload_reset_percentage: None,
            payload_reset_preset_mode: None,
            percentage_command_template: None,
            percentage_command_topic: None,
            percentage_state_topic: None,
            percentage_value_template: None,
            preset_mode_command_template: None,
            preset_mode_command_topic: None,
            preset_mode_state_topic: None,
            preset_mode_value_template: None,
            preset_modes: None,
            qos: None,
            retain: None,
            speed_range_max: None,
            speed_range_min: None,
            state_topic: None,
            state_value_template: None,
            unique_id: None,
        }
    }
}


