/*
 * Data structures for Home Assistant MQTT discovery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LightDevice {
    /// A link to the webpage that can manage the configuration of this device. Can be either an `http://`, `https://` or an internal `homeassistant://` URL.
    #[serde(rename = "configuration_url", skip_serializing_if = "Option::is_none")]
    pub configuration_url: Option<String>,
    /// A list of connections of the device to the outside world as a list of tuples `[connection_type, connection_identifier]`. For example the MAC address of a network interface: `\"connections\": [[\"mac\", \"02:5b:26:a8:dc:12\"]]`.
    #[serde(rename = "connections", skip_serializing_if = "Option::is_none")]
    pub connections: Option<Vec<String>>,
    #[serde(rename = "identifiers", skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<Box<crate::models::ButtonDeviceIdentifiers>>,
    /// The manufacturer of the device.
    #[serde(rename = "manufacturer", skip_serializing_if = "Option::is_none")]
    pub manufacturer: Option<String>,
    /// The model of the device.
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// The name of the device.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The firmware version of the device.
    #[serde(rename = "sw_version", skip_serializing_if = "Option::is_none")]
    pub sw_version: Option<String>,
}

impl LightDevice {
    pub fn new() -> LightDevice {
        LightDevice {
            configuration_url: None,
            connections: None,
            identifiers: None,
            manufacturer: None,
            model: None,
            name: None,
            sw_version: None,
        }
    }
}


