/*
 * Data structures for Home Assistant MQTT discovery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Lock {
    /// A list of MQTT topics subscribed to receive availability (online/offline) updates. Must not be used together with `availability_topic`.
    #[serde(rename = "availability", skip_serializing_if = "Option::is_none")]
    pub availability: Option<Vec<crate::models::AlarmControlPanelAvailabilityInner>>,
    /// When `availability` is configured, this controls the conditions needed to set the entity to `available`. Valid entries are `all`, `any`, and `latest`. If set to `all`, `payload_available` must be received on all configured availability topics before the entity is marked as online. If set to `any`, `payload_available` must be received on at least one configured availability topic before the entity is marked as online. If set to `latest`, the last `payload_available` or `payload_not_available` received on any configured availability topic controls the availability. (Default: `latest)`
    #[serde(rename = "availability_mode", skip_serializing_if = "Option::is_none")]
    pub availability_mode: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract device's availability from the `availability_topic`. To determine the devices's availability result of this template will be compared to `payload_available` and `payload_not_available`.
    #[serde(rename = "availability_template", skip_serializing_if = "Option::is_none")]
    pub availability_template: Option<String>,
    /// The MQTT topic subscribed to receive availability (online/offline) updates. Must not be used together with `availability`.
    #[serde(rename = "availability_topic", skip_serializing_if = "Option::is_none")]
    pub availability_topic: Option<String>,
    /// A regular expression to validate a supplied code when it is set during the service call to `open`, `lock` or `unlock` the MQTT lock.
    #[serde(rename = "code_format", skip_serializing_if = "Option::is_none")]
    pub code_format: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to generate the payload to send to `command_topic`. The lock command template accepts the parameters `value` and `code`. The `value` parameter will contain the configured value for either `payload_open`, `payload_lock` or `payload_unlock`. The `code` parameter is set during the service call to `open`, `lock` or `unlock` the MQTT lock and will be set `None` if no code was passed.
    #[serde(rename = "command_template", skip_serializing_if = "Option::is_none")]
    pub command_template: Option<String>,
    /// The MQTT topic to publish commands to change the lock state.
    #[serde(rename = "command_topic")]
    pub command_topic: String,
    #[serde(rename = "device", skip_serializing_if = "Option::is_none")]
    pub device: Option<Box<crate::models::ButtonDevice>>,
    /// Flag which defines if the entity should be enabled when first added. (Default: `true)`
    #[serde(rename = "enabled_by_default", skip_serializing_if = "Option::is_none")]
    pub enabled_by_default: Option<bool>,
    /// The encoding of the payloads received and published messages. Set to `\"\"` to disable decoding of incoming payload. (Default: `utf-8)`
    #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    /// The [category](https://developers.home-assistant.io/docs/core/entity#generic-properties) of the entity. (Default: `None)`
    #[serde(rename = "entity_category", skip_serializing_if = "Option::is_none")]
    pub entity_category: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract the JSON dictionary from messages received on the `json_attributes_topic`. Usage example can be found in [MQTT sensor](/integrations/sensor.mqtt/#json-attributes-template-configuration) documentation.
    #[serde(rename = "json_attributes_template", skip_serializing_if = "Option::is_none")]
    pub json_attributes_template: Option<String>,
    /// The MQTT topic subscribed to receive a JSON dictionary payload and then set as sensor attributes. Usage example can be found in [MQTT sensor](/integrations/sensor.mqtt/#json-attributes-topic-configuration) documentation.
    #[serde(rename = "json_attributes_topic", skip_serializing_if = "Option::is_none")]
    pub json_attributes_topic: Option<String>,
    /// The name of the lock. Can be set to `null` if only the device name is relevant. (Default: `MQTT Lock)`
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Used instead of `name` for automatic generation of `entity_id`
    #[serde(rename = "object_id", skip_serializing_if = "Option::is_none")]
    pub object_id: Option<String>,
    /// Flag that defines if lock works in optimistic mode. (Default: ``true` if no `state_topic` defined, else `false`.)`
    #[serde(rename = "optimistic", skip_serializing_if = "Option::is_none")]
    pub optimistic: Option<bool>,
    /// The payload that represents the available state. (Default: `online)`
    #[serde(rename = "payload_available", skip_serializing_if = "Option::is_none")]
    pub payload_available: Option<String>,
    /// The payload sent to the lock to lock it. (Default: `LOCK)`
    #[serde(rename = "payload_lock", skip_serializing_if = "Option::is_none")]
    pub payload_lock: Option<String>,
    /// The payload that represents the unavailable state. (Default: `offline)`
    #[serde(rename = "payload_not_available", skip_serializing_if = "Option::is_none")]
    pub payload_not_available: Option<String>,
    /// The payload sent to the lock to unlock it. (Default: `UNLOCK)`
    #[serde(rename = "payload_unlock", skip_serializing_if = "Option::is_none")]
    pub payload_unlock: Option<String>,
    /// The payload sent to the lock to open it. (Default: `OPEN)`
    #[serde(rename = "payload_open", skip_serializing_if = "Option::is_none")]
    pub payload_open: Option<String>,
    /// A special payload that resets the state to `unknown` when received on the `state_topic`. (Default: `\"None\")`
    #[serde(rename = "payload_reset", skip_serializing_if = "Option::is_none")]
    pub payload_reset: Option<String>,
    /// The maximum QoS level to be used when receiving and publishing messages.
    #[serde(rename = "qos", skip_serializing_if = "Option::is_none")]
    pub qos: Option<i32>,
    /// If the published message should have the retain flag on or not.
    #[serde(rename = "retain", skip_serializing_if = "Option::is_none")]
    pub retain: Option<bool>,
    /// The payload sent to `state_topic` by the lock when it's jammed. (Default: `JAMMED)`
    #[serde(rename = "state_jammed", skip_serializing_if = "Option::is_none")]
    pub state_jammed: Option<String>,
    /// The payload sent to `state_topic` by the lock when it's locked. (Default: `LOCKED)`
    #[serde(rename = "state_locked", skip_serializing_if = "Option::is_none")]
    pub state_locked: Option<String>,
    /// The payload sent to `state_topic` by the lock when it's locking. (Default: `LOCKING)`
    #[serde(rename = "state_locking", skip_serializing_if = "Option::is_none")]
    pub state_locking: Option<String>,
    /// The MQTT topic subscribed to receive state updates. It accepts states configured with `state_jammed`, `state_locked`, `state_unlocked`, `state_locking` or `state_unlocking`.
    #[serde(rename = "state_topic", skip_serializing_if = "Option::is_none")]
    pub state_topic: Option<String>,
    /// The payload sent to `state_topic` by the lock when it's unlocked. (Default: `UNLOCKED)`
    #[serde(rename = "state_unlocked", skip_serializing_if = "Option::is_none")]
    pub state_unlocked: Option<String>,
    /// The payload sent to `state_topic` by the lock when it's unlocking. (Default: `UNLOCKING)`
    #[serde(rename = "state_unlocking", skip_serializing_if = "Option::is_none")]
    pub state_unlocking: Option<String>,
    /// An ID that uniquely identifies this lock. If two locks have the same unique ID, Home Assistant will raise an exception.
    #[serde(rename = "unique_id", skip_serializing_if = "Option::is_none")]
    pub unique_id: Option<String>,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) to extract a state value from the payload.
    #[serde(rename = "value_template", skip_serializing_if = "Option::is_none")]
    pub value_template: Option<String>,
}

impl Lock {
    pub fn new(command_topic: String) -> Lock {
        Lock {
            availability: None,
            availability_mode: None,
            availability_template: None,
            availability_topic: None,
            code_format: None,
            command_template: None,
            command_topic,
            device: None,
            enabled_by_default: None,
            encoding: None,
            entity_category: None,
            json_attributes_template: None,
            json_attributes_topic: None,
            name: None,
            object_id: None,
            optimistic: None,
            payload_available: None,
            payload_lock: None,
            payload_not_available: None,
            payload_unlock: None,
            payload_open: None,
            payload_reset: None,
            qos: None,
            retain: None,
            state_jammed: None,
            state_locked: None,
            state_locking: None,
            state_topic: None,
            state_unlocked: None,
            state_unlocking: None,
            unique_id: None,
            value_template: None,
        }
    }
}


