/*
 * Data structures for Home Assistant MQTT discovery
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Tag {
    /// The MQTT topic subscribed to receive tag scanned events.
    #[serde(rename = "topic")]
    pub topic: String,
    /// Defines a [template](/docs/configuration/templating/#using-templates-with-the-mqtt-integration) that returns a tag ID.
    #[serde(rename = "value_template", skip_serializing_if = "Option::is_none")]
    pub value_template: Option<String>,
    #[serde(rename = "device")]
    pub device: Box<crate::models::BinarySensorDevice>,
}

impl Tag {
    pub fn new(topic: String, device: crate::models::BinarySensorDevice) -> Tag {
        Tag {
            topic,
            value_template: None,
            device: Box::new(device),
        }
    }
}


