{ inputs,  pkgs, ... }:

{
  env.HOME_ASSISTANT_DOCS = "${inputs.home-assistant-docs}";
  packages = [
    pkgs.bun
    pkgs.openapi-generator-cli
    pkgs.vscode
  ];

  languages.rust = {
    enable = true;
    channel = "stable";
  };

  pre-commit.hooks.rustfmt.enable = true;

  scripts.generate.exec = ''
    cat ${inputs.home-assistant-core}/homeassistant/components/mqtt/abbreviations.py \
        | sed 's|^""".*|// Do not edit this file, it has been generated from `homeassistant/components/mqtt/abbreviations.py` |g' \
        | sed -E 's/^([A-Za-z0-9_]+)\s*=/export const \1 =/g' \
        > $DEVENV_ROOT/generate-openapi-specs/src/abbreviations.ts

    cd $DEVENV_ROOT/generate-openapi-specs
    bun run src/index.ts

    cd $DEVENV_ROOT
    openapi-generator-cli generate -g rust -o test -i specs/openapi.yml --skip-validate-spec
  '';
}
